return {
    "folke/tokyonight.nvim",
    "nordtheme/vim",
    "morhetz/gruvbox",
    "tomasr/molokai",
    "rebelot/kanagawa.nvim",
    "cocopon/iceberg.vim",
    "colepeters/spacemacs-theme.vim",
    "tiagovla/tokyodark.nvim",
    "marko-cerovac/material.nvim",
    "bluz71/vim-moonfly-colors",
    "fynnfluegge/monet.nvim",
    "deankinane/blaze.nvim",
    "altercation/vim-colors-solarized",
}