-- local cppTools = require 'nt-cpp-tools'
--
-- vim.keymap.set("n", "<leader>qd", function()
--     vim.cmd("TSCppDefineClassFunc");
-- end)
--
-- vim.keymap.set("n", "<leader>qc", function()
--     vim.cmd("TSCppMakeConcreteClass");
-- end)
